server: 
  port: 8081
  servlet:
    context-path: /tontisa-lyboss
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ttx_lyboss?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non-null
  redis:
    host: 192.168.110.54
    port: 6379
    
    