ttx.lyboss.domain=http://p7dluzko9.bkt.clouddn.com/
ttx.lyboss.defaultBucket=lxk-op
ttx.lyboss.accessKey=3Od7caTw_KU23Rc_CcfY8rzkDHCta4e-KMJlypOu
ttx.lyboss.secretKey=ZlkIC40wej963x1Dt1u0cSjQtpjMFTrdZ0SGCe64
ttx.lyboss.qiniucallbackEnabled=ZlkIC40wej963x1Dt1u0cSjQtpjMFTrdZ0SGCe64